export const ADD = 'ADD'
export const CHANGE = 'CHANGE'
export const DISPLAY = 'DISPLAY'
export const OPEN = 'OPEN'
export const PRONOUNCE = 'PRONOUNCE'
export const TRANSLATE = 'TRANSLATE'

export const _BOOK = '_BOOK'
export const _FORM = '_FORM'
export const _LIST = '_LIST'
export const _ORIGINAL = '_ORIGINAL'
export const _READER = '_READER'
export const _TEXT = '_TEXT'
export const _TITLE = '_TITLE'

export const _START = '_START'
export const _DONE = '_DONE'
export const _FAIL = '_FAIL'
